---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/operator-sdk version
    register: operator_sdk_test_output
  - debug:
      msg: '{{ operator_sdk_test_output.stdout }}'
