---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ operator_sdk_url }} to {{ operator_sdk_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ operator_sdk_url }}'
    dest: '{{ operator_sdk_installed_exe }}'
    checksum: '{{ operator_sdk_checksum }}'
    mode: '755'
- name: Linking {{ operator_sdk_link }} to {{ operator_sdk_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ operator_sdk_installed_exe }}'
    dest: '{{ operator_sdk_link }}'
    state: link
